### ISSUE TITLE
No inheritance?

### ISSUE THREAD

**Issue by dangoodman** [ractivejs/component-spec#10]
It's not clear from out of the specification how to write a single-file component inheriting another one. It seems it's not possible at all. Am I missing something?

**Comment by martypdx** [comment]
See [this issues](https://github.com/ractivejs/rvc/issues/5) over in rvc.

It really depends on the loader you're using. I was using `ractive-load` at the time, and did create a version that could handle inheritance. Would be happy to share or give you some pointers based on what loader you're using.

I don't use component inheritance anymore, I've found that using by composition and with the really good  `{{yield}}` semantics components offer, I don't really need it.

**Comment by fskreuz** [comment]
Same here. I ended up creating "components that contain components" in order to extend a component's functionality. For instance, creating 2 mp3 players, one with UI controls and the other had plain text controls. Both will share the same mp3 player, but differ in controls. I'd do it like so:

headless-player.html
```html
<div>
  <audio src="{{ src }}" />
</div>
<!-- logic for controlling the audio element -->
```

ui-player.html
```html
<div>
  <headless-player src="{{ src }}" />
  <ui-player-controls on-play="playHeadlesPlayer" />
</div>
<!-- logic that connects the two -->
```

text-player.html
```html
<div>
  <headless-player src="{{ src }}" />
  <text-player-controls on-play="playHeadlesPlayer" />
</div>
<!-- logic that connects the two -->
```

**Comment by dangoodman** [comment]
Yeah, it seems in most cases composition and partials overrides will work better. Maybe inheritance doesn't worth to be implemented at all. Ractive do support component inheritance though (with `parent.extend({..})`) so it might be just more consistent to support it with component loaders too. It seems it might be worth to include a section into `author.md` about current state of single-file component inheritance and a few tips regarding composition.

Would be glad if you would share your way to achieve inheritance with `ractive-load` if you don't mind.

**Comment by fskreuz** [comment]
> Maybe inheritance doesn't worth to be implemented at all.

Ractive's inheritance works fine. That is why the issue pointed by @martypdx is filed under the rvc repo. *It's rvc's limitation*.

It's also worth remembering that Ractive is a library, not a framework. It gives you all that power, but doesn't force you to write in a single convention. Inheritance is provided to you, but you don't necessarily have to use it.

> It seems it might be worth to include a section into author.md about current state of single-file component inheritance and a few tips regarding composition.

Loaders are independently developed. Keeping track of all of them would be a cat-and-mouse game. It's best if loader implementers themselves document what they support.

It's similar to JS/HTML/CSS specs. We have a spec list (HTML5, ES6 etc.), but it's not standards body's job to list down support. It's the individual vendors and enthusiastic developers that maintain this list of supported features.

**Comment by dangoodman** [comment]
Sure, it works. It just not clear how to make it work with single-file components. Literally, I have no idea on how to get a single-file component extending another one. Do you? 

Or do you mean that's an implementation detail and therefore the issue should be addressed to a certain loader implementation? If so then how it differs from `component.exports` which **is** mentioned in the specification. I assume inheritance if implemented would work with something like `component.base` as suggested in the rvc's issue you mentioned.

**Comment by Rich-Harris** [comment]
I guess it *would* make sense to have some shared convention around this, since the library does in fact support inheritance from subclasses (though I'm also in the 'composition over inheritance' camp!). `component.base` is probably as good an idea as any.

I think it'd just be a matter of component loaders doing something like this:

```js
const options = extend( component.exports, { css, template });
export default ( component.base || Ractive ).extend( options );
```

As @fskreuz says though it'll still be down to individual loaders to either implement or ignore.

**Comment by martypdx** [comment]
@dangoodman Here's what I added to rcu [more or less here](https://github.com/ractivejs/rcu/blob/master/src/make.js#L60-L68) (the code has changed since I implemented this):

```js
base = component.base;

if ( typeof base === 'string' ) {
	base = Ractive.components[base];
	if ( !base ) {
		throw new Error( 'Component requested to extend from "' + component.base + '" which was not found on Ractive.components')
	}
}

Component = (base || Ractive).extend( options );
```

Then in component file:

```js
component.base = 'board';
component.exports = {
...
};
```

The issue is that there's no built in dependency ordering, so ractive-load had to be explicitly used:

```js
return Ractive.load('components/board.html')
    .then(function(board){

        Ractive.components.board = board
        return Ractive.load('components/display-board.html')

    })
    .then(function(display){

        Ractive.components['display-board'] = display;
        return Ractive.load('components/grid-total.html')

    })
    .then(function(total){

        Ractive.components['grid-total'] = total;
        return Ractive.load()

    })
```

IMO the future is using the module system to handle dependencies and move away from `component.exports = { ... }`. 

It made sense at the time, but not anymore...

**Comment by dangoodman** [comment]
@martypdx Thank you. I'll try this.

**Comment by ghost** [comment]
Closing. Components general lean towards composition rather than inheritance.
