### ISSUE TITLE
Partials

### ISSUE THREAD

**Issue by guilhermeaiolfi** [ractivejs/component-spec#8]
Hi,

How should I declare partials in my component definition? There is no mention in the spec. 

https://github.com/blackgate/ractive-componentify uses:

``` html
<link rel="ractive" href="path/to/_mypartial.ract">
{{>mypartial}}
```

I'm creating my reactive + SystemJS loader (https://github.com/guilhermeaiolfi/ractem) and would like to know the "right" way of doing that. 

Thanks.

**Comment by Rich-Harris** [comment]
Thanks, this should be documented. The way to define partials within the template is to use a 'partial block':

```html
{{>myPartial}}

{{#partial myPartial}}
  <p>this is my partial</p>
{{/partial}}
```

Incidentally, you can define inline partials inside components, which makes the partial definition available to that component:

```html
<FancyList items='{{items}}'>
  {{#partial item}}
    <!-- the FancyList component will repeat this block for each item,
         overriding the default item partial (if there is one) -->
    <li class='neato'>{{description}}</li>
  {{/partial}}
</FancyList>
```

Here's an example: http://examples.ractivejs.org/8c4ff8a7488a558f4a85

**Comment by guilhermeaiolfi** [comment]
So how ractive-componentify import partials shouldn't be considered? 

Sometimes the partial is a very large portion of code and would be best placed in its own file.

**Comment by Rich-Harris** [comment]
To be honest I wasn't aware that ractive-componentify was doing it that way. At first I thought the `_` prefix was a bit offputting, and that something like `<link rel='ractive' href='...' type='partial'>` would be better, but on reflection I'm not so sure - whether a file defines a partial or a component is intrinsic to that file and nothing to do with how it's consumed, so a naming convention that identifies a file as being a partial rather than a component does make sense.

(I've also wondered about ditching `<link>` altogether and just using `require()` instead, though that would make it rather more difficult for components to be environment-agnostic.)

So I don't think I'd be opposed to the convention ractive-componentify uses. Would welcome other opinions before we make it an 'official' thing though!

An alternative solution is to just use it as a component instead:

```html
<link rel='ractive' href='./MyPartial.html'>

<!-- not actually a partial, but might as well be. The contents
     of MyPartial.html are the same either way -->
<MyPartial/>
```

**Comment by blackgate** [comment]
Hi,

Author of ractive-componentify here.

The reasons behind the choice of a naming convention instead of an attribute are mainly because it's easier to distinguish from components, and it makes the imports implicit, which means you can't import a partial as a component if you forget the type attribute for example.

**Comment by ghost** [comment]
The various ways of defining partials are now documented in the docs.
